//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.ComponentModel;

namespace WebApi.Module {

	[JsonObject(MemberSerialization.OptIn)]
	public class Tbiz_PersonalInfo {

		/// <summary>
		/// 用户主键
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)", IsPrimary = true)]
		public string UserId { get; set; } = string.Empty;

		/// <summary>
		/// 账户锁定标示
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string AcctLock { get; set; } = string.Empty;

		/// <summary>
		/// 批次号
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string BatchNum { get; set; } = string.Empty;

		/// <summary>
		/// 出生日期
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Birthday { get; set; } = string.Empty;

		/// <summary>
		/// 居住地址
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string CaddressHome { get; set; } = string.Empty;

		/// <summary>
		/// 主证件地址（默认身份证地址）
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string CaddressNid { get; set; } = string.Empty;

		/// <summary>
		/// 公司邮箱
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CcompEmail { get; set; } = string.Empty;

		/// <summary>
		/// 公司主键
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CompanyId { get; set; } = string.Empty;

		/// <summary>
		/// 使用格式
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(120)")]
		public string CountryNmForm { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? CreateDate { get; set; }

		/// <summary>
		/// 邮箱
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Email { get; set; } = string.Empty;

		/// <summary>
		/// 性别
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Gender { get; set; } = string.Empty;

		/// <summary>
		/// 最高教育程度
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string HighestEducLvl { get; set; } = string.Empty;

		[JsonProperty, Column(IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 婚姻状况
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string MarStatus { get; set; } = string.Empty;

		/// <summary>
		/// 结婚日期
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string MarStatusDt { get; set; } = string.Empty;

		/// <summary>
		/// 手机
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Mobile { get; set; } = string.Empty;

		/// <summary>
		/// 主证件ID
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string NationalId { get; set; } = string.Empty;

		/// <summary>
		/// 用户ID
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Operator { get; set; } = string.Empty;

		/// <summary>
		/// 姓名
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(120)")]
		public string RealName { get; set; } = string.Empty;

		/// <summary>
		/// 集合ID
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string SetId { get; set; } = string.Empty;

		/// <summary>
		/// 固定电话
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Telephone { get; set; } = string.Empty;

	}

}
