//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.ComponentModel;

namespace WebApi.Module {

	[JsonObject(MemberSerialization.OptIn)]
	public class Tbiz_JobInfoLog {

		[JsonProperty, Column(IsPrimary = true, IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 批次号
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string BatchNum { get; set; } = string.Empty;

		/// <summary>
		/// 业务子类
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CbusinessSub { get; set; } = string.Empty;

		/// <summary>
		/// 业务类型
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CbusinessType { get; set; } = string.Empty;

		/// <summary>
		/// 条线划分
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CdividingLine { get; set; } = string.Empty;

		/// <summary>
		/// 岗位ID
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CquartersId { get; set; } = string.Empty;

		/// <summary>
		/// 岗位序列
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CquteOrder { get; set; } = string.Empty;

		/// <summary>
		/// 岗位简称
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CquteShortName { get; set; } = string.Empty;

		/// <summary>
		/// 岗位子序列
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CquteSonOrder { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? CreateDate { get; set; }

		/// <summary>
		/// 状态
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Cstate { get; set; } = string.Empty;

		/// <summary>
		/// 岗位名称
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Descr { get; set; } = string.Empty;

		/// <summary>
		/// 生效日期
		/// </summary>
		[JsonProperty, Column(DbType = "date")]
		public DateTime? Effdt { get; set; }

		/// <summary>
		/// 职务代码
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string JobCode { get; set; } = string.Empty;

		/// <summary>
		/// 集合id
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string SetId { get; set; } = string.Empty;

	}

}
