//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.ComponentModel;

namespace WebApi.Module {

	[JsonObject(MemberSerialization.OptIn)]
	public class Tbiz_PositionLevelLog {

		[JsonProperty, Column(IsPrimary = true, IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 批次号
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string BatchNum { get; set; } = string.Empty;

		/// <summary>
		/// 控股职级；此列用于表示城市公司的职级与控股统一要求的职级的对应关系
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CholdingRank { get; set; } = string.Empty;

		/// <summary>
		/// 角色编码
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Code { get; set; } = string.Empty;

		/// <summary>
		/// 职级代码
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string CrankCode { get; set; } = string.Empty;

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty]
		public DateTime? CreateDate { get; set; }

		/// <summary>
		/// 职级简短描述
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string DescrShort { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "date")]
		public DateTime? Effdt { get; set; }

		/// <summary>
		/// 有效
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Enabled { get; set; } = string.Empty;

		/// <summary>
		/// 角色名称
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string FullName { get; set; } = string.Empty;

		/// <summary>
		/// 集合 ID
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string SetId { get; set; } = string.Empty;

	}

}
