//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.ComponentModel;

namespace WebApi.Module {

	[JsonObject(MemberSerialization.OptIn)]
	public class Tbiz_JsonLog {

		[JsonProperty, Column(IsPrimary = true, IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty]
		public DateTime? CreateDate { get; set; }

		/// <summary>
		/// json字符串
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(MAX)")]
		public string JsonString { get; set; } = string.Empty;

		/// <summary>
		/// 接口名
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(500)")]
		public string MethodName { get; set; } = string.Empty;

	}

}
