//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.ComponentModel;

namespace WebApi.Module {

	/// <summary>
	/// 机构单位表
	/// </summary>
	[JsonObject(MemberSerialization.OptIn)]
	public class LR_Base_Company {

		/// <summary>
		/// 公司主键
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
		public string F_CompanyId { get; set; } = string.Empty;

		/// <summary>
		/// 详细地址
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_Address { get; set; } = string.Empty;

		/// <summary>
		/// 经营范围
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(200)")]
		public string F_BusinessScope { get; set; } = string.Empty;

		/// <summary>
		/// 公司分类
		/// </summary>
		[JsonProperty]
		public int? F_Category { get; set; }

		/// <summary>
		/// 市主键
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_CityId { get; set; } = string.Empty;

		/// <summary>
		/// 县/区主键
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_CountyId { get; set; } = string.Empty;

		/// <summary>
		/// 创建日期
		/// </summary>
		[JsonProperty]
		public DateTime? F_CreateDate { get; set; }

		/// <summary>
		/// 创建用户主键
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_CreateUserId { get; set; } = string.Empty;

		/// <summary>
		/// 创建用户
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_CreateUserName { get; set; } = string.Empty;

		/// <summary>
		/// 删除标记
		/// </summary>
		[JsonProperty]
		public int? F_DeleteMark { get; set; }

		/// <summary>
		/// 备注
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(200)")]
		public string F_Description { get; set; } = string.Empty;

		/// <summary>
		/// 电子邮箱
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_Email { get; set; } = string.Empty;

		/// <summary>
		/// 有效标志
		/// </summary>
		[JsonProperty]
		public int? F_EnabledMark { get; set; }

		/// <summary>
		/// 公司代码
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_EnCode { get; set; } = string.Empty;

		/// <summary>
		/// 传真
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_Fax { get; set; } = string.Empty;

		/// <summary>
		/// 成立时间
		/// </summary>
		[JsonProperty]
		public DateTime? F_FoundedTime { get; set; }

		/// <summary>
		/// 公司名称
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_FullName { get; set; } = string.Empty;

		/// <summary>
		/// 内线电话
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_InnerPhone { get; set; } = string.Empty;

		/// <summary>
		/// 负责人
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_Manager { get; set; } = string.Empty;

		/// <summary>
		/// 修改日期
		/// </summary>
		[JsonProperty]
		public DateTime? F_ModifyDate { get; set; }

		/// <summary>
		/// 修改用户主键
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_ModifyUserId { get; set; } = string.Empty;

		/// <summary>
		/// 修改用户
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_ModifyUserName { get; set; } = string.Empty;

		/// <summary>
		/// 公司性质
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_Nature { get; set; } = string.Empty;

		/// <summary>
		/// 外线电话
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_OuterPhone { get; set; } = string.Empty;

		/// <summary>
		/// 父级主键
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_ParentId { get; set; } = string.Empty;

		/// <summary>
		/// 邮编
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_Postalcode { get; set; } = string.Empty;

		/// <summary>
		/// 省主键
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_ProvinceId { get; set; } = string.Empty;

		/// <summary>
		/// 公司简称
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string F_ShortName { get; set; } = string.Empty;

		/// <summary>
		/// 排序码
		/// </summary>
		[JsonProperty]
		public int? F_SortCode { get; set; }

		/// <summary>
		/// 公司主页
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(200)")]
		public string F_WebAddress { get; set; } = string.Empty;

	}

}
